### ISSUE TITLE
Table Header Cells do not have a grey background anymore

### ISSUE THREAD

**Issue by AxelMKlein** [BurningTreeC/tiddlywiki-printriver#1]
When I print a tiddler with the Printriver plugin now, header cells in tables do not have a grey background anymore.
This holds true for the printed pdf, the preview is still okay.
This worked previously, but does not anymore.
Of course I am not sure whether that's an issue of the Printriver-plugin.

I am using Tiddlywiki 5.2.0 and Printriver 0.2.2.

Thank you in advance

**Comment by BurningTreeC** [comment]
Hi @AxelMKlein and really sorry for the very late reply!

I'll investigate this, seems to be a CSS issue

**Comment by BurningTreeC** [comment]
Hi @AxelMKlein 

I've tried this out in my Firefox browser.
In fact, when I print the table header background disappears.
But I have the option to print backgrounds, it's in the print options way down.
That solved it for me.

**Comment by AxelMKlein** [comment]
Hi BurningTreeC,

Thank you so much for the recommendation and resolution.
It works as you propose also in Vivaldi in Ubuntu here.
Great plugin!
Best regards
Axel

**Comment by AxelMKlein** [comment]
Solved by BurningTreeC.
